yolo:
  weights: "runs/detect_train/weights/best.pt"
  imgsz: 640
  conf: 0.25
  use_type: true
  device: "0" # <- pakai GPU 0 (ROCm)

ocr:
  langs: ["id", "en"]
  min_width: 1400
  debug_dir: "debug_out"
  text_threshold: 0.7
  low_text: 0.3
  slope_ths: 0.2
  mag_ratio: 1.5

heuristic_roi:
  ktp_left_ratio: 0.78
  nik_top_ratio: 0.22

server:
  host: "0.0.0.0"
  port: 8604
  debug: false
