version: '3.8'

services:
  ocr-engine-service:
    build: .
    ports:
      - "8604:8604"
    environment:
      - PORT=8604
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - PIN_OCR_CONFIG=config.yaml
      - LOG_LEVEL=DEBUG
      - CUDA_VISIBLE_DEVICES=0
    volumes:
      - ./debug_out:/app/debug_out
      - ./uploads:/app/uploads
      - ./runs:/app/runs
      - ./config.yaml:/app/config.yaml:ro
      - ./test_images:/app/test_images:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8604/health/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # GPU support (uncomment jika ada GPU dan nvidia-docker)
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # Development tools
  ocr-test:
    build: .
    profiles:
      - testing
    command: python -m pytest tests/ -v --cov=.
    environment:
      - FLASK_ENV=testing
      - PIN_OCR_CONFIG=config.example.yaml
    volumes:
      - .:/app
    depends_on:
      - ocr-engine-service

volumes:
  debug_out:
  uploads:
  runs:
