apiVersion: v1
kind: Namespace
metadata:
  name: mediq-production
  labels:
    name: mediq-production
    environment: production
    app: mediq
  annotations:
    description: "MediQ Application Production Environment"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: mediq-production-quota
  namespace: mediq-production
spec:
  hard:
    requests.cpu: "8"
    requests.memory: 16Gi
    limits.cpu: "16"
    limits.memory: 32Gi
    persistentvolumeclaims: "20"
    pods: "30"
    services: "15"
    secrets: "15"
    configmaps: "15"
---
apiVersion: v1
kind: LimitRange
metadata:
  name: mediq-production-limits
  namespace: mediq-production
spec:
  limits:
  - default:
      cpu: "2"
      memory: 4Gi
    defaultRequest:
      cpu: 500m
      memory: 1Gi
    type: Container
  - default:
      storage: 20Gi
    type: PersistentVolumeClaim
