apiVersion: v1
kind: ConfigMap
metadata:
  name: ktp-templates
  labels:
    app: ocr-engine-service
    component: templates
data:
  ktp-template-v1.json: |
    {
      "name": "Indonesian KTP Template v1.0",
      "description": "Standard Indonesian National ID Card template for OCR processing",
      "version": "1.0",
      "fields": [
        {
          "name": "nik",
          "label": "NIK",
          "type": "text",
          "required": true,
          "pattern": "^[0-9]{16}$",
          "position": {
            "x": 120,
            "y": 80,
            "width": 200,
            "height": 25
          },
          "validation": {
            "minLength": 16,
            "maxLength": 16,
            "dataType": "numeric"
          }
        },
        {
          "name": "nama",
          "label": "Nama",
          "type": "text",
          "required": true,
          "position": {
            "x": 120,
            "y": 110,
            "width": 250,
            "height": 25
          },
          "validation": {
            "minLength": 2,
            "maxLength": 100,
            "dataType": "alphabetic_with_spaces"
          }
        },
        {
          "name": "tempat_lahir",
          "label": "Tempat Lahir",
          "type": "text",
          "required": true,
          "position": {
            "x": 120,
            "y": 140,
            "width": 150,
            "height": 25
          },
          "validation": {
            "minLength": 2,
            "maxLength": 50,
            "dataType": "alphabetic_with_spaces"
          }
        },
        {
          "name": "tanggal_lahir",
          "label": "Tanggal Lahir",
          "type": "date",
          "required": true,
          "pattern": "^[0-9]{2}-[0-9]{2}-[0-9]{4}$",
          "position": {
            "x": 280,
            "y": 140,
            "width": 100,
            "height": 25
          },
          "validation": {
            "format": "DD-MM-YYYY",
            "minYear": 1900,
            "maxYear": 2024
          }
        },
        {
          "name": "jenis_kelamin",
          "label": "Jenis Kelamin",
          "type": "enum",
          "required": true,
          "values": ["LAKI-LAKI", "PEREMPUAN"],
          "position": {
            "x": 120,
            "y": 170,
            "width": 100,
            "height": 25
          }
        },
        {
          "name": "golongan_darah",
          "label": "Gol. Darah",
          "type": "enum",
          "required": false,
          "values": ["A", "B", "AB", "O", "-"],
          "position": {
            "x": 280,
            "y": 170,
            "width": 50,
            "height": 25
          }
        },
        {
          "name": "alamat",
          "label": "Alamat",
          "type": "text",
          "required": true,
          "position": {
            "x": 120,
            "y": 200,
            "width": 250,
            "height": 50
          },
          "validation": {
            "minLength": 10,
            "maxLength": 200
          }
        },
        {
          "name": "rt_rw",
          "label": "RT/RW",
          "type": "text",
          "required": true,
          "pattern": "^[0-9]{3}/[0-9]{3}$",
          "position": {
            "x": 120,
            "y": 260,
            "width": 80,
            "height": 25
          }
        },
        {
          "name": "kel_desa",
          "label": "Kel/Desa",
          "type": "text",
          "required": true,
          "position": {
            "x": 120,
            "y": 290,
            "width": 120,
            "height": 25
          },
          "validation": {
            "minLength": 2,
            "maxLength": 50
          }
        },
        {
          "name": "kecamatan",
          "label": "Kecamatan",
          "type": "text",
          "required": true,
          "position": {
            "x": 120,
            "y": 320,
            "width": 120,
            "height": 25
          },
          "validation": {
            "minLength": 2,
            "maxLength": 50
          }
        },
        {
          "name": "agama",
          "label": "Agama",
          "type": "enum",
          "required": true,
          "values": ["ISLAM", "KRISTEN", "KATOLIK", "HINDU", "BUDDHA", "KHONGHUCU"],
          "position": {
            "x": 280,
            "y": 290,
            "width": 100,
            "height": 25
          }
        },
        {
          "name": "status_perkawinan",
          "label": "Status Perkawinan",
          "type": "enum",
          "required": true,
          "values": ["BELUM KAWIN", "KAWIN", "CERAI HIDUP", "CERAI MATI"],
          "position": {
            "x": 280,
            "y": 320,
            "width": 100,
            "height": 25
          }
        },
        {
          "name": "pekerjaan",
          "label": "Pekerjaan",
          "type": "text",
          "required": true,
          "position": {
            "x": 120,
            "y": 350,
            "width": 150,
            "height": 25
          },
          "validation": {
            "minLength": 2,
            "maxLength": 50
          }
        },
        {
          "name": "kewarganegaraan",
          "label": "Kewarganegaraan",
          "type": "enum",
          "required": true,
          "values": ["WNI", "WNA"],
          "position": {
            "x": 280,
            "y": 350,
            "width": 80,
            "height": 25
          }
        },
        {
          "name": "berlaku_hingga",
          "label": "Berlaku Hingga",
          "type": "text",
          "required": true,
          "values": ["SEUMUR HIDUP"],
          "position": {
            "x": 120,
            "y": 380,
            "width": 120,
            "height": 25
          }
        }
      ],
      "preprocessing": {
        "denoise": true,
        "deskew": true,
        "contrast_enhancement": true,
        "resize": {
          "width": 400,
          "height": 250
        },
        "crop": {
          "x": 10,
          "y": 10,
          "width": 380,
          "height": 230
        }
      },
      "validation_rules": [
        {
          "field": "nik",
          "rule": "luhn_check",
          "description": "NIK must pass Luhn algorithm check"
        },
        {
          "field": "tanggal_lahir",
          "rule": "date_consistency",
          "description": "Birth date must be consistent with NIK encoding"
        },
        {
          "field": "alamat",
          "rule": "address_completeness",
          "description": "Address must contain street and area information"
        }
      ],
      "confidence_thresholds": {
        "minimum_field_confidence": 0.7,
        "minimum_overall_confidence": 0.8,
        "critical_fields": ["nik", "nama", "tanggal_lahir"]
      }
    }

  ktp-regions.json: |
    {
      "provinces": {
        "11": "ACEH",
        "12": "SUMATERA UTARA",
        "13": "SUMATERA BARAT",
        "14": "RIAU",
        "15": "JAMBI",
        "16": "SUMATERA SELATAN",
        "17": "BENGKULU",
        "18": "LAMPUNG",
        "19": "KEPULAUAN BANGKA BELITUNG",
        "21": "KEPULAUAN RIAU",
        "31": "DKI JAKARTA",
        "32": "JAWA BARAT",
        "33": "JAWA TENGAH",
        "34": "DI YOGYAKARTA",
        "35": "JAWA TIMUR",
        "36": "BANTEN",
        "51": "BALI",
        "52": "NUSA TENGGARA BARAT",
        "53": "NUSA TENGGARA TIMUR",
        "61": "KALIMANTAN BARAT",
        "62": "KALIMANTAN TENGAH",
        "63": "KALIMANTAN SELATAN",
        "64": "KALIMANTAN TIMUR",
        "65": "KALIMANTAN UTARA",
        "71": "SULAWESI UTARA",
        "72": "SULAWESI TENGAH",
        "73": "SULAWESI SELATAN",
        "74": "SULAWESI TENGGARA",
        "75": "GORONTALO",
        "76": "SULAWESI BARAT",
        "81": "MALUKU",
        "82": "MALUKU UTARA",
        "91": "PAPUA BARAT",
        "94": "PAPUA"
      },
      "gender_codes": {
        "01-31": "LAKI-LAKI",
        "41-71": "PEREMPUAN"
      },
      "birth_date_encoding": {
        "description": "Day of birth encoding in NIK",
        "male": "DD (as is)",
        "female": "DD + 40"
      }
    }

  ocr-preprocessing.json: |
    {
      "image_preprocessing": {
        "steps": [
          {
            "name": "resize",
            "params": {
              "max_width": 2048,
              "max_height": 2048,
              "maintain_aspect_ratio": true
            }
          },
          {
            "name": "grayscale",
            "params": {
              "enabled": true
            }
          },
          {
            "name": "noise_reduction",
            "params": {
              "method": "gaussian_blur",
              "kernel_size": 3
            }
          },
          {
            "name": "contrast_enhancement",
            "params": {
              "method": "histogram_equalization",
              "clip_limit": 2.0
            }
          },
          {
            "name": "deskew",
            "params": {
              "enabled": true,
              "angle_tolerance": 15
            }
          },
          {
            "name": "edge_detection",
            "params": {
              "method": "canny",
              "low_threshold": 50,
              "high_threshold": 150
            }
          },
          {
            "name": "morphological_operations",
            "params": {
              "operation": "opening",
              "kernel_size": 2
            }
          }
        ]
      },
      "text_extraction": {
        "ocr_engine": "tesseract",
        "language": "ind+eng",
        "page_segmentation_mode": 6,
        "oem": 3,
        "confidence_threshold": 30,
        "whitelist_chars": "0123456789ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz -/.,:();",
        "blacklist_chars": "!@#$%^&*+=[]{}|\\\"'<>?_`~"
      },
      "post_processing": {
        "text_cleaning": {
          "remove_extra_spaces": true,
          "normalize_line_breaks": true,
          "fix_common_ocr_errors": true
        },
        "field_extraction": {
          "use_template_matching": true,
          "use_regex_patterns": true,
          "use_position_mapping": true
        },
        "validation": {
          "field_format_validation": true,
          "cross_field_validation": true,
          "data_integrity_checks": true
        }
      }
    }
