apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway
  namespace: mediq
  labels:
    app: api-gateway
    service: api-gateway
spec:
  replicas: 2
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
      - name: api-gateway
        image: mediq/api-gateway:latest
        ports:
        - containerPort: 8601
          name: http
        envFrom:
        - configMapRef:
            name: api-gateway-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8601
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8601
          initialDelaySeconds: 5
          periodSeconds: 5
