apiVersion: apps/v1
kind: Deployment
metadata:
  name: ocr-service
  namespace: mediq
  labels:
    app: ocr-service
    service: ocr-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ocr-service
  template:
    metadata:
      labels:
        app: ocr-service
    spec:
      containers:
      - name: ocr-service
        image: mediq/ocr-service:latest
        ports:
        - containerPort: 8603
          name: http
        envFrom:
        - configMapRef:
            name: ocr-service-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8603
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8603
          initialDelaySeconds: 5
          periodSeconds: 5
