apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ocr-models-pvc
  namespace: mediq
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard
