apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
  namespace: mediq
  labels:
    app: user-service
    service: user-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: mediq/user-service:latest
        ports:
        - containerPort: 8602
          name: http
        envFrom:
        - configMapRef:
            name: user-service-config
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8602
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8602
          initialDelaySeconds: 5
          periodSeconds: 5
