apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: mediq
  labels:
    app: user-service
spec:
  type: ClusterIP
  ports:
  - port: 8602
    targetPort: 8602
    protocol: TCP
    name: http
  selector:
    app: user-service
