apiVersion: v1
kind: ConfigMap
metadata:
  name: ocr-engine-config
  labels:
    app: ocr-engine-service
data:
  # OCR Engine Configuration
  YOLO_WEIGHTS: "runs/detect_train/weights/best.pt"
  YOLO_IMGSZ: "640"
  YOLO_CONF: "0.25"
  YOLO_USE_TYPE: "true"
  YOLO_DEVICE: "0"
  
  # OCR Configuration
  OCR_LANGS: "id,en"
  OCR_MIN_WIDTH: "1400"
  OCR_DEBUG_DIR: "debug_out"
  OCR_TEXT_THRESHOLD: "0.7"
  OCR_LOW_TEXT: "0.3"
  OCR_SLOPE_THS: "0.2"
  OCR_MAG_RATIO: "1.5"
  
  # ROI Configuration
  KTP_LEFT_RATIO: "0.78"
  NIK_TOP_RATIO: "0.22"
  
  # Server Configuration
  SERVER_HOST: "0.0.0.0"
  SERVER_PORT: "8604"
  SERVER_DEBUG: "false"
  
  # Performance Tuning
  MAX_WORKERS: "4"
  WORKER_TIMEOUT: "300"
  MAX_REQUESTS: "1000"
  
  # Security
  MAX_FILE_SIZE: "10MB"
  ALLOWED_EXTENSIONS: "jpg,jpeg,png,webp"
  
  # Logging
  LOG_LEVEL: "INFO"
  LOG_FORMAT: "json"

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: yolo-model-weights
  labels:
    app: ocr-engine-service
    component: ml-model
binaryData:
  # YOLO model weights akan di-mount sebagai file
  # Dalam production, ini akan di-populate dari model registry
  best.pt: ""
