name: __SERVICE_NAME__ CI/CD Pipeline

on:
  push:
    branches: [ main, develop ]
    paths: 
      - '__SERVICE_PATH__/**'
      - '.github/workflows/__SERVICE_WORKFLOW__'
  pull_request:
    branches: [ main ]
    paths:
      - '__SERVICE_PATH__/**'

env:
  SERVICE_NAME: __SERVICE_NAME__
  SERVICE_PATH: __SERVICE_PATH__
  DOCKER_IMAGE: __DOCKER_IMAGE__
  PORT: __PORT__

jobs:
  test:
    name: Test & Build
    runs-on: ubuntu-latest
    
    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: mediq_test
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

      rabbitmq:
        image: rabbitmq:3.13-management
        env:
          RABBITMQ_DEFAULT_USER: guest
          RABBITMQ_DEFAULT_PASS: guest
        ports:
          - 5672:5672
          - 15672:15672
        options: >-
          --health-cmd="rabbitmq-diagnostics -q ping"
          --health-interval=30s
          --health-timeout=10s
          --health-retries=5

      redis:
        image: redis:7-alpine
        ports:
          - 6379:6379
        options: >-
          --health-cmd="redis-cli ping"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: ${{ env.SERVICE_PATH }}/package-lock.json

    - name: Install dependencies
      run: |
        cd ${{ env.SERVICE_PATH }}
        npm ci

    - name: Generate Prisma Client (if applicable)
      run: |
        cd ${{ env.SERVICE_PATH }}
        if [ -f "prisma/schema.prisma" ]; then
          npx prisma generate
          npx prisma db push --force-reset
        fi
      env:
        DATABASE_URL: mysql://root:root@localhost:3306/mediq_test

    - name: Run ESLint
      run: |
        cd ${{ env.SERVICE_PATH }}
        npm run lint

    - name: Run Prettier Check
      run: |
        cd ${{ env.SERVICE_PATH }}
        npm run format

    - name: Run Unit Tests
      run: |
        cd ${{ env.SERVICE_PATH }}
        npm run test:cov
      env:
        NODE_ENV: test
        DATABASE_URL: mysql://root:root@localhost:3306/mediq_test
        RABBITMQ_URL: amqp://guest:guest@localhost:5672
        REDIS_URL: redis://localhost:6379
        JWT_SECRET: test-secret-key-for-jwt-token-generation
        JWT_REFRESH_SECRET: test-refresh-secret-key-for-jwt-refresh-token

    - name: Run Integration Tests
      run: |
        cd ${{ env.SERVICE_PATH }}
        npm run test:integration
      env:
        NODE_ENV: test
        DATABASE_URL: mysql://root:root@localhost:3306/mediq_test
        RABBITMQ_URL: amqp://guest:guest@localhost:5672
        REDIS_URL: redis://localhost:6379
        JWT_SECRET: test-secret-key-for-jwt-token-generation
        JWT_REFRESH_SECRET: test-refresh-secret-key-for-jwt-refresh-token

    - name: Build Application
      run: |
        cd ${{ env.SERVICE_PATH }}
        npm run build

    - name: Upload Coverage to Codecov
      uses: codecov/codecov-action@v4
      with:
        file: ${{ env.SERVICE_PATH }}/coverage/lcov.info
        name: ${{ env.SERVICE_NAME }}-coverage
        fail_ci_if_error: false

  security-scan:
    name: Security Scan
    runs-on: ubuntu-latest
    needs: test

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Dependency Check
      uses: dependency-check/Dependency-Check_Action@main
      with:
        project: ${{ env.SERVICE_NAME }}
        path: ${{ env.SERVICE_PATH }}
        format: 'JSON'
        args: >
          --enableRetired
          --enableExperimental
          --out dependency-check-report

    - name: Upload Dependency Check Results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: dependency-check-results
        path: dependency-check-report

    - name: Run npm audit
      run: |
        cd ${{ env.SERVICE_PATH }}
        npm audit --audit-level=high

  docker-build:
    name: Docker Build & Push
    runs-on: ubuntu-latest
    needs: [test, security-scan]
    if: github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_TOKEN }}

    - name: Extract metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.DOCKER_IMAGE }}
        tags: |
          type=ref,event=branch
          type=ref,event=pr
          type=sha,prefix={{branch}}-
          type=raw,value=latest,enable={{is_default_branch}}

    - name: Build and push Docker image
      uses: docker/build-push-action@v5
      with:
        context: ${{ env.SERVICE_PATH }}
        file: ${{ env.SERVICE_PATH }}/Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.DOCKER_IMAGE }}:latest
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: docker-build
    if: github.ref == 'refs/heads/main'
    environment: staging

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Staging
      run: |
        echo "Deploying ${{ env.SERVICE_NAME }} to staging..."
        echo "Image: ${{ env.DOCKER_IMAGE }}:main-${{ github.sha }}"
        # Add your deployment commands here
        # Example: kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$DOCKER_IMAGE:main-${{ github.sha }}

  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: github.ref == 'refs/heads/main'
    environment: 
      name: production
      url: https://api.mediq.id

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Deploy to Production
      run: |
        echo "Deploying ${{ env.SERVICE_NAME }} to production..."
        echo "Image: ${{ env.DOCKER_IMAGE }}:main-${{ github.sha }}"
        # Add your production deployment commands here
        # Example: kubectl set image deployment/$SERVICE_NAME $SERVICE_NAME=$DOCKER_IMAGE:main-${{ github.sha }}

    - name: Health Check
      run: |
        echo "Running health check for ${{ env.SERVICE_NAME }}..."
        # Add health check commands here
        # Example: curl -f http://production-url/health
